version: '3.8'

services:
  app:
    image: cadastro-app:latest  # Nome da imagem do aplicativo Spring Boot
    container_name: cadastro-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Mapeamento direto da porta 3000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bdusuario  # Nome do serviço MySQL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - mysql  # Aguarda o banco de dados estar disponível antes de iniciar o app
    restart: always  # Reinicia automaticamente o contêiner se ele falhar
    
